name: PR Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: neuralnorthwest/actions/test-go@main
