name: PR Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'
    paths:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: neuralnorthwest/actions/test-go@main
        with:
          no-cache: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: neuralnorthwest/actions/lint-go@main
        with:
          no-cache: true
